# Generated by Django 3.2.4 on 2021-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_productcustomfield_snipcartsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snipcartsettings',
            name='api_key',
            field=models.CharField(help_text='Your snipcart public API key', max_length=255),
        ),
    ]
